---
title: 'Quantitative Finance'
output:
  pdf_document:
    template: template-alt.tex
  html_document:
    df_print: paged
---

# Probability theory overview

## Cumulative distribution function (cdf)

Every real-valued random variable $X$ can be described by its cumulative distribution function $(c d f) F_{X}: \mathbb{R} \rightarrow[0,1]$ defined as
$$
F_{X}(x)=\mathbb{P}[X \leq x]
$$
Notice that, as mentioned above, $\{X \leq x\}=X^{-1}((-\infty, x]) \in \mathcal{F}$.

### Discrete random variable \

We call var. discrete, if its image (pmf) is **finite** or **countably finite**.

### Continuos random variables \

We call radom var continuos if its cdf is contunous. It implies the image of X (pdf) is "uncountably infite".

## Quantile functions and quantiles \

Quantile is **generalized inverse of the cdf $F_x$ of X, defined as:
$$
Q_{X}(p)=\inf \left\{x \in \mathbb{R} \mid p \leq F_{X}(x)\right\}
$$

For some probability level $\alpha\epsilon(0,1)$, the $\alpha-quantile$ is just the value $Q_x(\alpha)$

## Expected Value \

or expectation, mean, average, first moment- characterises the tendency or long-run average value


### For absolutely continuous

$$
\mathbb{E}[X]=\int_{-\infty}^{\infty} x f_{X}(x) d x
$$

### For discrete

$$
\mathbb{E}[X]=\sum_{k=1}^{\infty} x_{k} \mathrm{P}\left[X=x_{k}\right]=\sum_{k=1}^{\infty} x_{k} p_{k}
$$

### Main take-home

Example. Let $X \sim \mathcal{U}(a, b)$, (uniformly distributed) then the expected value of $X$ is
$$
\begin{aligned}
\mathbb{E}[X] &=\int_{-\infty}^{\infty} x f_{X}(x) \mathrm{d} x=\int_{a}^{b} \frac{x}{b-a} \mathrm{~d} x=\left.\frac{x^{2}}{2(b-a)}\right|_{x=a} ^{b} \\
&=\frac{b^{2}-a^{2}}{2(b-a)}=\frac{a+b}{2}
\end{aligned}
$$
$$ 
\mathbb{E}[X] = \frac{a+b}{2}
$$


## Variance and SD

- variance: distance to the mean, expecteation of the squared devation from its mean
- standard devation: sqare root of variance

$$
\operatorname{Var}(X)=\mathbb{V}[X]=\mathbb{E}\left[(X-\mathbb{E}[X])^{2}\right]
$$
$$
\operatorname{Var}(X)=\frac{(b-a)^2}{12}
$$

## Covariance between two RV \

expected value of the product of their SD. 

$$
\operatorname{cov}(X, Y)=\frac{\sigma_{X Y}=\sigma(X, Y)}{N-1}=\frac{\mathbb{E}[(X-\mathbb{E}[X])(Y-\mathbb{E}[Y])]}{N-1}
$$
$$
\operatorname{cov}(X, Y)= \frac{\mathbb{E}[XY]-\mathbb{E}[X]\mathbb{E}[Y]}{N-1}
$$

## Pearson's correlation \

Measure of linear correlation betwewen two RV.

$$
\rho_{X, Y}=\frac{\operatorname{cov}(X, Y)}{\sqrt{\mathbb{V}[X]} \sqrt{\mathbb{V}[Y]}}=\frac{\sigma_{X, Y}}{\sigma_{X} \sigma_{Y}}
$$

! **If two vars are independent, they are also uncorrelated, the opposite must not be true.**

$$
\mathrm{V}[X+Y] =\mathbb{V}[X]+\mathbb{V}[Y]+2 \operatorname{cov}(X, Y)
$$
Note that variance of a sum is sum of variance only if vars are uncorrelated.

## Skewness \

Measure of the assymetry of the distribution around its mean. Third standardized moment.

$$
\gamma_{1}(X)=\mathbb{E}\left[\left(\frac{X-\mathbb{E}[X]}{\sqrt{\mathrm{V}[X]}}\right)^{3}\right]=\mathbb{E}\left[\left(\frac{X-\mu}{\sigma}\right)^{3}\right]
$$

## Kurtosis \

Measure of the width of its tails. Fourth standadized moment. Kurtosis = 3 is average, above (below) is excess kurtosis.

$$
\operatorname{Kurt}[X]=\gamma_{2}(X)=\kappa(X)=\mathbb{E}\left[\left(\frac{X-\mu}{\sigma}\right)^{4}\right]
$$

## Independence

We say two elements $A$ and $B$ of a $\sigma$ -algebra are independent and we write $A \perp B$ if
$$
\mathbb{P}[A \cap B]=\mathbb{P}[A] \mathbb{P}[B]
$$
To see why we call this property independence, we recall the definition of the conditional probability and use 'independence',
$$
\mathbb{P}[A \mid B]=\frac{\mathbb{P}[A \cap B]}{\mathbb{P}[B]}=\frac{\mathbb{P}[A] \mathbb{P}[B]}{\mathbb{P}[B]}=\mathbb{P}[A]
$$
So the probability of $A$ stays the same independent of the occurrence of
$B$. The same is true the other way around
$$
\mathbb{P}[B \mid A]=\frac{\mathbb{P}[B \cap A]}{\mathbb{P}[A]}=\mathbb{P}[B]
$$

## Normal distribution

### probability density function \

$$
f_{X}(x)=\frac{1}{\sqrt{2 \pi \sigma^{2}}} \exp \left(-\frac{(x-\mu)^{2}}{2 \sigma^{2}}\right) .
$$

### density function , cdf\
$$
\varphi(x)=\frac{1}{\sqrt{2 \pi}} \exp \left(-\frac{x^{2}}{2}\right)
$$



### Combined 

$$
f_{X}(x)=\frac{1}{\sigma} \varphi\left(\frac{x-\mu}{\sigma}\right)
$$

## Log-normal distribution

$$
\begin{aligned}
&\text { We say } X \text { is log-normally distributed and write } X \sim \log \mathcal{N}\left(\mu, \sigma^{2}\right) \text { if }\\
&Y=\log (X) \sim \mathcal{N}\left(\mu, \sigma^{2}\right)
\end{aligned}
$$
$$
f(x)=\frac{1}{x \sqrt{2 \pi \sigma^{2}}} \exp \left[-\frac{(\log x-\mu)^{2}}{2 \sigma^{2}}\right]
$$

## t-distribution

Like normal but with heavier tails.

### cdf

$$
t_{\nu}(x)=\int_{-\infty}^{x} \frac{\Gamma\left(\frac{\nu+1}{2}\right) \nu^{\frac{\nu}{2}}}{\sqrt{\pi} \Gamma\left(\frac{\nu}{2}\right)}\left(\nu+t^{2}\right)^{-\frac{\nu+1}{2}} \mathrm{~d} t
$$
Where $\nu$ denotes the degrees of freedom.


# Bonds

## Present value of Zero coupon bonds

$$
PV(y)=\frac{C_{T}}{(1+y)^{T}}
$$

Notes:

- market value of zero-coupon bonds decreases with longer maturities
- keeping T fixed, the market value of the zero-coupon bond decreases as the yield increases

Semi-annual compounding (e.g. used in the U.S. Treasury bond market): interest rate $y_{s}$ is derived from:
$$
P\left(y_{s}\right)=\frac{C_{T}}{\left(1+\frac{y_{s}}{2}\right)^{2 T}}
$$
Continuous compounding (used ubiquitously in the quantitative finance literature) interest rate $y_{c}$ is derived from:
$$
P\left(y_{c}\right)=\frac{C_{T}}{\exp \left(y_{c} T\right)}=e^{-y_{c} T} C_{T}
$$
$yield = ({\frac{FV}{C_T}})^\frac{1}{T}-1$

$$
1+y_{p.a.} = (1+\frac{y_{p.s.}}{2})^2=exp(y_{continous})
$$
**Price of a coupon paying bond** 

$$
P(y)=\frac{c F}{y}\left(1-\frac{1}{(1+y)^{T}}\right)+\frac{F}{(1+y)^{T}}
$$
Price of a perpetual bond/consol:
$P(y)=\frac{c}{y}F$

## Taylor series

$$
\begin{aligned}
T_{f, x_{0}}(x) &=\sum_{n=0}^{\infty} \frac{f^{(n)}\left(x_{0}\right)}{n !}\left(x-x_{0}\right)^{n} \\
&=f\left(x_{0}\right)+f^{\prime}\left(x_{0}\right)\left(x-x_{0}\right)+\frac{f^{\prime \prime}\left(x_{0}\right)}{2}\left(x-x_{0}\right)^{2}+\ldots
\end{aligned}
$$
$$
\sum_{n=0}^{2} \frac{f^{(n)}\left(x_{0}\right)}{n !}\left(x-x_{0}\right)^{n}=f\left(x_{0}\right)+f^{\prime}\left(x_{0}\right)\left(x-x_{0}\right)+\frac{f^{\prime \prime}\left(x_{0}\right)}{2}\left(x-x_{0}\right)^{2}
$$
a Taylor polynomial of degree two and so on.

## Duration  

$\triangleright$ The Dollar-Duration $(D D)$ is the negative of the first derivative
$$
D D(y)=-P^{\prime}(y)
$$
$\triangleright$ The Modified Duration $\left(D^{*}\right)$ is a normalized version of the Dollar-Duration:
$$
D^{*}(y)=\frac{D D(y)}{P(y)}=-\frac{P^{\prime}(y)}{P(y)}
$$
$\triangleright$ The Macaulay Duration $\left(D_{M}\right)$, yet another normalized version:
$$
D_{M}(y)=(1+y) D^{*}(y)=-(1+y) \frac{P^{\prime}(y)}{P(y)}
$$

Duration is average cash-flow during maturity, or average time at which cash is received. Measures sensitivity to change in yields.

## Convexity

Improved approximation of bond price sensitivity given by duration. Taylor series up to the second derivative. Hence: 
$\triangleright$ Again, we take the second derivative of each term in the sum separately. We get for all $t \in\{1, \ldots, T\}$,
$$
\frac{\mathrm{d}^{2}}{\mathrm{~d} y^{2}}\left(\frac{C_{t}}{(1+y)^{t}}\right)=\frac{\mathrm{d}}{\mathrm{d} y}\left(-\frac{t C_{t}}{(1+y)^{t+1}}\right)=\frac{t(t+1) C_{t}}{(1+y)^{t+2}}
$$
$\unrhd$ Hence, the second derivative of the bond price is given by
$$
\begin{aligned}
P^{\prime \prime}(y) &=\frac{\mathrm{d}^{2} P}{\mathrm{~d} y^{2}}(y)=\sum_{t=1}^{T} \frac{t(t+1) C_{t}}{(1+y)^{t+2}}=\frac{1}{(1+y)^{2}} \sum_{t=1}^{T} \frac{t(t+1) C_{t}}{(1+y)^{t}} \\
&=\frac{1}{(1+y)^{2}}\left(\frac{2 C_{1}}{1+y}+\frac{6 C_{2}}{(1+y)^{2}}+\ldots+\frac{T(T+1) C_{n}}{(1+y)^{T}}\right) .
\end{aligned}
$$

#### Dollar convexity 

$(D C)$ is defined as the second derivative of the bond price with respect to the yield, that means we set

$$
D C(y)=\frac{\mathrm{d}^{2} P}{\mathrm{~d} y^{2}}(y)=P^{\prime \prime}(y)
$$
#### Bond convexity 

$(\kappa)$ is defined to be the second derivative of the bond price with respect to the yield, divided by the bond price, that is
 
$$
\kappa(y)=\frac{D C(y)}{P(y)}=\frac{P^{\prime \prime}(y)}{P(y)}
$$
Note that some practitioners refer to convexity as the second derivative divided by the present value and additionally multiplied by the factor $\frac{1}{2}$

#### Zero Coupon convexity

$$
\kappa(y)=\frac{(T+1) T}{(1+y)^{2}}
$$


### Conclusions:

- for small movements, duration (linear approx.) is reasonably good.
- dollar duration measures the negative slope of the tanget to the price-yield curve at the point $y_0$
- duration is the **average time to wait for each payment weighted by their present values**

# Econometrics (volatility)


- vol alludes to the fact that asset price, thus the return, is **random**
- vol is a measure of uncertainty of the stock returns
- typical vol of stocks is between 20-50%
- matters for rebalancing positions

## Stylized facts

- returns of stocks exhibit **heteroscedasticity and positive autocorrelation**
- volatility clusters - large (small) vol is followed by also large(small) vol, of either sign
- autocorrelations are not large and decrease more or less slowly with the lag order

## Intro

Unbiased estimator of the variance

$$
\widehat{v}=\frac{1}{n-1} \sum_{i=1}^{n}\left(u_{i}-\bar{u}\right)^{2}
$$

The annualized volatility $\widehat{\sigma}$, under the assumption of Gaussianity, can be estimated as
$$
\widehat{\sigma}=\frac{\sqrt{v}}{\sqrt{\tau}}
$$
 $SE= \frac{\widehat{\sigma}}{\sqrt{2 n}}$.


## ARCH(m)

- captures dependence in the form of positive autocorrelations in the square residuals
- estimate of the variance is based on LT average variance and m observations. The older it is, less weight it's given.

### Creation

$$
\sigma_{n}^{2}=\sum_{i=1}^{m} \alpha u_{n-i}^{2}
$$
$\triangleright$ The coefficient $\alpha_{i}>0$ is the weight given to the observation $i$ days ago. **Alpha serves to give higher weights to more recent observations** \

Extension is the assumption there is a long-run variance rate and that it should be given some weight.

$$
\sigma_{n}^{2}=\gamma V_{L}+\sum_{i=1}^{m} \alpha_{i} u_{n-i}^{2}
$$
where $V_{L}$ is the long-run variance rate and $\gamma$ is the weight assigned to $V_{L}$. Often, $\omega=\gamma V_L$.
Because the weights must sum to unity, we have
$$
\gamma+\sum_{i=1}^{m} \alpha_{i}=1 .
$$

### EWMA Model

- designed to track changes in the volatility

Weights $\alpha_i$ **decrease exponentially** as we move back through time.

$$
\alpha_{i+1}=\lambda \alpha_{i}, \text { where } \lambda \in[0,1]
$$
It turns out that this weighting scheme leads to a particularly simple formula for updating volatility estimates:
$$
\sigma_{n}^{2}=\lambda \sigma_{n-1}^{2}+(1-\lambda) u_{n-1}^{2}
$$

$$
\sigma_{n}^{2}=(1-\lambda) \sum_{i=1}^{m} \lambda^{i-1} u_{n-i}^{2}+\lambda^{m} \sigma_{n-m}^{2}
$$

Lambda is empirically at 0.94.

### GARCH (1,1)

- vol. clustering often generates more extreme values and less central values compared to case when returns are independent, i.e. $\alpha=\beta=0$
- incorporates mean-reversion, whereas EWMA does not

The conditional variance $\sigma_{t}^{2}$ is calculated from a long-run average variance rate $V_{L}$, the past variance $\sigma_{t-1}^{2}$, and the past return $u_{t-1}$ :
$$
\sigma_{t}^{2}=\underbrace{\gamma \cdot V_{L}}_{\omega}+\beta \cdot \sigma_{t-1}^{2}+\alpha \cdot u_{t-1}^{2}, \quad 
$$

Where:

- conditional variance $\sigma_{t-1}^{2}$ is calculated from the LT average $V_L$, past return $u_{t-1}$
- 1 = $\gamma+\beta+\alpha$

# Copulas

Correlation measures only **linear dependency**- copulas solve this problem.

### Definition
Copulas are functions that separate the **marginal distributions** from the **dependency structure** of a multivar distribution \

Copulas express dependence on a **quantile scale**- useful for dependence of **extreme outcomes**. They facilite **bottom-up approach**- that is better because we often understand marginal behavior of individual risk factors than the aggregate, whole dependence structure.

### Definition 2

Coupula is a function with 2 vars and has 3 properties:

- groundedness
- margins
- increasing

## Grounded functions

### Definition. 

We say a function $H: X \times Y \rightarrow \mathbb{R}$ is grounded if
$$
H\left(x, m_{Y}\right)=H\left(m_{X}, y\right)=0 \text { for all }(x, y) \in X \times Y
$$
Example. Let $H:[-1,1] \times[0, \infty] \rightarrow \mathbb{R}$ be defined by
$$
H(x, y)=\frac{(x+1)\left(e^{y}-1\right)}{x+2 e^{y}-1}
$$
Then $H$ is grounded, since $H(x, 0)=H(-1, y)=0$ for all $x \in[-1,1]$ and $y \in[0, \infty]$.

## Margins

Suppose now that $M_{X}=\max X$ and $M_{Y}=\max Y$ exist.

### Definition. 

The margins of a function $H: X \times Y \rightarrow \mathbb{R}$ are the functions
$$
\begin{array}{l}
F: X \rightarrow \mathbb{R} \text { defined by } F(x)=H\left(x, M_{Y}\right) \text { and } \\
G: Y \rightarrow \mathbb{R} \text { defined by } G(y)=H\left(M_{X}, y\right)
\end{array}
$$

## 2-increasing functions

### Definition. 

Let $A=\left[x_{1}, x_{2}\right] \times\left[y_{1}, y_{2}\right] \subset X \times Y$. The $H$ -volume of the rectangle $A$ is defined as
$$
V_{H}(A)=H\left(x_{2}, y_{2}\right)-H\left(x_{2}, y_{1}\right)-H\left(x_{1}, y_{2}\right)+H\left(x_{1}, y_{1}\right) .
$$
We abbreviate this as
$$
V_{H}(A)=\Delta_{y_{1}}^{y_{2}} \Delta_{x_{1}}^{x_{2}} H(x, y)
$$
for the first order differences of $H$ on $A$.
$\Delta_{x_{1}}^{x_{2}} H(x, y)=H\left(x_{2}, y\right)-H\left(x_{1}, y\right)$ and $\Delta_{y_{1}}^{y_{2}} H(x, y)=H\left(x, y_{2}\right)-H\left(x, y_{1}\right) .$
We call a function $H: X \times Y \rightarrow \mathbb{R}$ 2-increasing 1 if $V_{H}(A) \geq 0$ for all rectangles $A \subset X \times Y$

## Summary of copulas with properties

Definition. A function $C:[0,1]^{2} \rightarrow[0,1]$ is called a copula (or more precisely, a two-dimensional copula, or a 2-copula) if
1. $C$ is grounded, that means $C(u, 0)=C(0, v)=0$,
2. Its margins are the identity, that means for every $u, v \in[0,1]$
$$
C(u, 1)=u \text { and } C(1, v)=v
$$
3. $C$ is 2 -increasing, that means for every $u_{1}, u_{2}, v_{1}, v_{2} \in[0,1]$ with $u_{1} \leq u_{2}, v_{1} \leq v_{2}$ we have
$$
C\left(u_{2}, v_{2}\right)-C\left(u_{2}, v_{1}\right)-C\left(u_{1}, v_{2}\right)+C\left(u_{1}, v_{1}\right) \geq 0
$$

## Types of copulas

Example. The fundamental examples are:
$\triangleright$ Product or independence copula: $\Pi(u, v)=u v$,
$\triangleright$ Lower Fréchet-Hoeffding bound: $W(u, v)=\max (u+v-1,0)$,
$\triangleright$ Upper Fréchet-Hoeffding bound: $M(u, v)=\min (u, v)$.

## Sklar's theorem

Theorem. (Sklar's theorem)
1. Let $H$ be a joint distribution function with margins $F$ and $G$. Then there exists a copula $C$ such that for all $x, y \in \overline{\mathbb{R}}$
$$
H(x, y)=C(F(x), G(y))
$$
If $F$ and $G$ are continuous, then $C$ is unique. Otherwise, $C$ is uniquely determined on $\operatorname{Ran} F \times \operatorname{Ran} G$, where $\operatorname{Ran} F$ denotes the range of $F$.
2. Conversely, if $C$ is a copula and $F$ and $G$ are distribution functions, then the function $H$, given in Equation (1), defines a joint distribution function with margins $F$ and $G$.

**THEN THE ASSOCIATED COPULA IS:**

$$
C(u, v)=\frac{u v}{u+v-u v}
$$
## Examples of copulas

- fundamental couplas: independent copula, upper and lower bounds
- implicit copulas: extracted from known cdf's F via Sklar's theorem. Cannot write C=..... directly.
- explicit copulas: can write C=... directly, but their use is very limited and they are quite unnecessary.

### Parametric copulas
We can divide parametric couplas into *implicit* and *explicit* ones.
Sklar's theorem states that we can always find a copula in a parametric distribution function.
Let $H$ be the distribution function and let $F_{1}, F_{2}$ its continuous margins.
Then the implied copula is
$$
C\left(u_{1}, u_{2}\right)=H\left(F_{1}^{(-1)}\left(u_{1}\right), F_{2}^{(-1)}\left(u_{2}\right)\right)
$$
Such a copula may not have a simple closed form.


### Financial interpretation

$\triangleright$ Consider 2 daily returns $X=\left(X_{1}, X_{2}\right)$ with pairwise correlations all equal to $\rho=0.5 .$ \

However, we are unsure about the best joint model.

$D$ If the copula of $X$ is $C_{\rho=0.5}^{\text {Gauss}}$ , the probability that on a given day both returns lie below their $\alpha=0.01$ quantiles is (this is a coupla)
$$
\mathbb{P}\left[X_{1} \leq F_{1}^{-1}(\alpha), X_{2} \leq F_{2}^{-1}(\alpha)\right]=\mathbb{P}\left[U_{1} \leq \alpha, U_{2} \leq \alpha\right] \approx 1.29 \times 10^{-3}
$$
In the long run such an event will happen approximately once every 775 trading days $(\approx$ once every 3 years \

$\triangleright$ If the copula of $X$ is $C_{\nu=4, \rho=0.5}^{t}$ (student distribution) however, such an event will happen approximately $2.22$ times more often, i.e. $\approx$ once every $1.3$ years.!!!!!

# Guest Lecture - Modelling dependencies

## Pearson correlation

$$
\rho\left(X_{1}, X_{2}\right)=\frac{\operatorname{Cov}\left(X_{1}, X_{2}\right)}{\sqrt{\operatorname{Var}\left(X_{1}\right) \operatorname{Var}\left(X_{2}\right)}}
$$

$\text { where } \operatorname{Cov}\left(X_{1}, X_{2}\right)=E\left(X_{1} X_{2}\right)-E\left(X_{1}\right) E\left(X_{2}\right)$

- parametric
- only captures linear dependeces (no tail risk)

## Spearman

$\rho_{S}\left(X_{1}, X_{2}\right)=\rho\left(F_{1}\left(X_{1}\right), F_{2}\left(X_{2}\right)\right)$

- not sensitive to outliers
-good for heavy tailed distributions

## Kendall

$\tau\left(X_{1}, X_{2}\right)=E\left[\operatorname{sign}\left(\left(X_{1}-\tilde{X}_{1}\right)\left(X_{2}-\tilde{X}_{2}\right)\right)\right]$
where $\tilde{X}_{1}$ and $\tilde{X}_{2}$ have the same joint distribution, but are independent of $X_{1}$ and $X_{2}$

- not sensitive to outliers
-good for heavy tailed distributions
- !**appropraite to measure tail behavior**

# Discrete Time Models

## Adaptedness and predictability \

We call an indexed family of RV a **stochastic process** \

$\triangleright$ A stochastic process $Z=\left(Z_{t}\right)_{t=0, \ldots, T}$ is called $\mathbb{F}$ -adapted if $Z_{t}$ is $\mathcal{F}_{\text {(J) measurable for every }} t=0, \ldots, T$.
$\triangleright$ A stochastic process $Y=\left(Y_{t}\right)_{t=1, \ldots, T}$ is called $\mathbb{F}$ -predictable if $Y_{t}$ is $\mathcal{F}_{(t-x)}-$ measurable for every $t=1, \ldots, T$
In our model, the price process $\bar{S}=\left(\bar{S}_{t}\right)_{t=0, \ldots, T}$ is $\mathbb{F}$ -adapted.

## Trading strategies \

$\sum \xi_{t}^{k}$ represents the number of shares of asset $k$ held during the $t^{\text {th }}$ trading period between times $t-1$ and $t$.
$\sum \xi_{t}^{k} S_{t-1}^{k}$ denotes the amount invested in the $k^{\text {th }}$ asset at time $t-1$, while $\xi_{t}^{k} S_{t}^{k}$ is the resulting value at time $t$.
D Predictability of the strategy represents the fact that any investment must be allocated at the beginning of each trading period, without anticipating future prices.

### Valuation process \


The (discounted) value process $V=\left(V_{t}\right)_{t \in\{0, \ldots, T\}}$ of a trading strategy $\bar{\xi}$ is given by
$\Rightarrow V_{0}=\bar{\xi}_{1} \cdot \bar{X}_{0}$ and $V_{t}=\bar{\xi}_{t} \cdot \bar{X}_{t}$ for $t=1, \ldots, T$
$V_{t}$ represents the portfolio value at the end of the $t^{\text {th }}$ trading period.


### Arbitrage opportunities 

Arbitrage is a self-financing, risk-free trading strategy such that: $V_0 \leq 0;V_T \geq 0$

### Martingale definition

Definition. Let $(\Omega, \mathcal{F}, \mathbb{F}, \mathbb{P})$ be a filtered probability space. Then a stochastic process $M=\left(M_{t}\right)_{t=0, \ldots, T}$ is called a (P, $\left.\mathbb{F}\right)$ -martingale if

$\triangleright M$ is $\mathbb{F}$ -adapted, \

$\triangleright$ $\mathbb{E}_{\mathbb{P}}\left[\left|M_{t}\right|\right]<\infty$ for every $t \in\{0, \ldots, T\}$ \
$\triangleright$ $\mathbb{E}_{\mathbf{P}}\left[M_{t} \mid \mathcal{F}_{s}\right]=M_{s}$, for all $0 \leq s \leq t \leq T$ \
Interpretation. The best prediction given the information up until now is exactly the current value. This is our definition of a 'fair game'.

**check whether $up+d-dp=0$, if not, not a margingale.** (probabilities of up-down with the values) \

Market is arbitrage free only if $d<r_f<u$

In this one-period binomial model, this means we search for a measure $\mathbb{P}^{*}$ identified by $\left(p^{*}, 1-p^{*}\right)$ such that
$$
p^{*} \frac{S_{0}(1+u)}{1+r}+\left(1-p^{*}\right) \frac{S_{0}(1+d)}{1+r}=S_{0}
$$
This is equivalent to
$$
p^{*}(1+u)+\left(1-p^{*}\right)(1+d)=1+r .
$$
## Binomial model

Solving for $p*$ from above: \

$$
p*=\frac{r-d}{u-d} \Leftrightarrow 1-p*=\frac{u-r}{u-d}; 
$$

### In the two period tree

$$
\begin{aligned}
100=200 p_{\mathrm{u}}^{*}+50 p_{\mathrm{d}}^{*} & \Longleftrightarrow p_{\mathrm{u}}^{*}=\frac{1}{3}, p_{\mathrm{d}}^{*}=\frac{2}{3} \\
200=300 p_{\mathrm{uu}}^{*}+150 p_{\mathrm{ud}}^{*} & \Longleftrightarrow p_{\mathrm{uu}}^{*}=\frac{1}{3}, p_{\mathrm{ud}}^{*}=\frac{2}{3} \\
50=60 p_{\mathrm{du}}^{*}+20 p_{\mathrm{dd}}^{*} & \Longleftrightarrow p_{\mathrm{du}}^{*}=\frac{3}{4}, p_{\mathrm{dd}}^{*}=\frac{1}{4}
\end{aligned}
$$

Where $p_u+p_d=1; p_u=1-p_d$

## Contingent claims (basically options) \

$$
\text { Pay-off CALL} \rightarrow \left(S_{T}-K\right)^{+}=\max \left(0, S_{T}-K\right) \text { . }
$$

$$
\text { Pay-off PUT} \rightarrow \left(S_{T}-K\right)^{+}=\max \left(0, K- S_{T}\right) \text { . }
$$

*Contigent claim* with maturity T is attaible(replicable) if there exists a self-financing strategy $\bar{\xi}$ whose terminal port. value coincides with $C_T$, that is

$$
C_{T}=\bar{\xi}_{T} \cdot \bar{S}_{T} \quad \mathbb{P}-\mathrm{a.s}
$$

$C_{T}$ is attainable if and only if its corresponding discounted claim $H_{T}=\frac{C_{T}}{(1+r)^{r}}$ can be written as
$$
H_{T}=\bar{\xi}_{T} \cdot \bar{X}_{T}=V_{T}=V_{0}+\sum_{t=1}^{T} \xi_{t} \cdot\left(X_{t}-X_{t-1}\right)
$$
for a self-financing trading strategy $\bar{\xi}$ with value process $V$.

The replicating strategy $\left(\overline{\xi_{1}}, \overline{\xi_{2}}\right)$ must satisfy the following:
1. The self-financing property $\overline{\xi_{1}} \cdot \bar{S}_{1}=\overline{\xi_{2}} \cdot \bar{S}_{1}$ :
$$
\begin{array}{l}
\xi_{1}^{0} \cdot B_{1}+\xi_{1}^{1} \cdot S_{1}\left(\omega_{u}\right)=\xi_{2}^{0} \cdot B_{1}+\xi_{2}^{1} \cdot S_{1}\left(\omega_{u}\right), \\
\xi_{1}^{0} \cdot B_{1}+\xi_{1}^{1} \cdot S_{1}\left(\omega_{d}\right)=\xi_{2}^{0} \cdot B_{1}+\xi_{2}^{1} \cdot S_{1}\left(\omega_{d}\right),
\end{array}
$$
2. The replicating property $C_{2}=\overline{\xi_{2}} \cdot \overline{S_{2}}$ :
$$
\xi_{2, u}^{0} \cdot B_{2}+\xi_{2, u}^{1} \cdot S_{2}\left(\omega_{u u}\right)=C_{2}\left(\omega_{u u}\right),
$$
$$
\begin{array}{l}
\xi_{2, u}^{0} \cdot B_{2}+\xi_{2, u}^{1} \cdot S_{2}\left(\omega_{u d}\right)=C_{2}\left(\omega_{u d}\right), \\
\xi_{2, d}^{0} \cdot B_{2}+\xi_{2, d}^{1} \cdot S_{2}\left(\omega_{d u}\right)=C_{2}\left(\omega_{d u}\right) \\
\xi_{2, d}^{0} \cdot B_{2}+\xi_{2, d}^{1} \cdot S_{2}\left(\omega_{d d}\right)=C_{2}\left(\omega_{d d}\right)
\end{array}
$$
## Arbitrage free prices

The goal is to price a discounted contigent claim $H_T$ without introducing arbitrage. If $H_T$ is attainble, the discounted initail investment needed for replicating $H_T$ is $\bar{\xi}_{1} \cdot \bar{X}_{0}=V_{0}=\mathbb{E}_{P^{*}}\left[H_{T}\right]$. It can be interpreted as the unique discounted arbitrage-free price for H.

## Put-call parity

At time $T$, one can observe that $K+\left(S_{T}-K\right)^{+}-\left(K-S_{T}\right)^{+}=S_{T}$ This implies that $V_{T}\left(P_{1}\right)=V_{T}\left(P_{2}\right)$.

** Put call parity** 
$$C_{t}-P_{t}=S_{t}-\frac{K B}{(1+r)^{t}} \Leftrightarrow K B_{t}+C_{t}-P_{t}=S_{t}$$

### Price of a european call:

$$
Price(call) = \frac{1}{1+r}\left(\frac{r-d}{u-d}\left((1+u) S_{0}-K\right)^{+}+\frac{u-r}{u-d}\left((1+d) S_{0}-K\right)^{+}\right)
$$

## Complete markets

*A multiperiod arbitrage-free market is called complete if every single contingent claim is attainable*

$\Rightarrow$ arbitrage-free model is complete *iff* there exists **just one equivalent martingale measure** (unique P)

## Replication \

Formal description of payoff (left) with the replication (right). We again search for the weights $\xi_{0,1}$.

$$\left(S_{1}-K\right)^{+}=\xi^{0} B_{1}+\xi^{1} S_{1}=\xi^{0}(1+r)+\xi^{1} S_{1}$$

$$
\begin{array}{l}
\xi^{0}=\frac{(1+u)\left(S_{0}(1+d)-K\right)^{+}-(1+d)\left(S_{0}(1+u)-K\right)^{+}}{(1+r)(u-d)}, \\
\xi^{1}=\frac{\left(S_{0}(1+u)-K\right)^{+}-\left(S_{0}(1+d)-K\right)^{+}}{S_{0}(u-d)}
\end{array}
$$

## T-period binomial model

$$
S_{t}(\omega)=S_{0} \cdot(1+u)^{j_{t}(\omega)}(1+d)^{t-j_{t}(\omega)},
$$
where $j_{t}(\omega)$ is the number of up-moves in a total of $t$ moves, when the
event $\omega$ occurs.

We can rewrite simple return as
$$
\begin{aligned}
R_{t}(\omega) &=\frac{S_{t}(\omega)-S_{t-1}(\omega)}{S_{t-1}(\omega)}=(1+d) \frac{1-Y_{t}(\omega)}{2}+(1+u) \frac{1+Y_{t}(\omega)}{2}-1 \\
&=\frac{1}{2}\left(d\left(1-Y_{t}(\omega)\right)+u\left(1+Y_{t}(\omega)\right)\right)=\left\{\begin{array}{ll}
u, & \text { if } Y_{t}(\omega)=1 \\
d, & \text { if } Y_{t}(\omega)=-1
\end{array}\right.
\end{aligned}
$$


The price process of the risky asset can be written as
$$
S_{t}=S_{0} \prod_{s=1}^{t}\left(1+R_{s}\right) .
$$
The discounted price process is of the form
$$
X_{t}=\frac{S_{t}}{B_{t}}=S_{0} \prod_{s=1}^{t} \frac{1+R_{s}}{1+r}=\frac{S_{0}}{(1+r)^{t}} \prod_{s=1}^{t}\left(1+R_{s}\right) .
$$

# Stochastic calculus and B-S model \

- discrete time stoch. procs. (binomial trees) are approximation of the continuos time stoch. process.
- continuos time models are **limit** of discrete time models when "n" goes to infity

## Brownian motion

Definition. A one-dimensional standard Brownian motion is a stochastic
process $\left(W_{t}\right)_{0 \leq t \leq T}$ with the following properties: \
1. $W_{0}=0$, \
2. $t \mapsto W_{t}(\omega)$ is a continuous function $\mathbb{P}$ -a.s.. \
3. $\left(W_{t}\right)_{0 \leq t \leq T}$ is adapted to the filtration $\left(\mathcal{F}_{t}\right)_{0 \leq t \leq T}$, \
4. !!!! the increments $W_{t}-W_{s}$ are independent and normally distributed with **variance $t-s$ and zero mean** for any $0 \leq s \leq t$. \
D Intuitively, the change of Brownian motion on the interval $(t, t+\Delta t)$ can be perceived as $\Delta W_{t}:=W_{t+\Delta t}-W_{t}=\epsilon \sqrt{\Delta t}$, where
$\epsilon \sim \mathcal{N}(0,1) .$

### Important properties of Brownian motion \

Martingale: Given the information up to $s<t$ the conditional expectation of $W_{t}$ is $W_{s}$, that is
$$
\mathbb{E}\left(W_{t} \mid \mathcal{F}_{s}\right)=W_{s}
$$
Q Quadratic variation: If we divide up the time interval $[0, t]$ into a partition $P$ with $n+1$ points $t_{i}$, then
$$
\langle W\rangle_{t}=\lim _{n \rightarrow \infty} \sum_{t_{i} \in P}\left(W_{t_{i}}-W_{t_{i-1}}\right)^{2} \underset{\text { a.s. }}{\longrightarrow} t
$$
Markov property: The conditional distribution of $W_{t}$ given information up until $s<t$ depends only on $W_{s}$. That is, for any event $A$ and $s<t$ it holds that
$$
\mathbb{P}\left(W_{t} \in A \mid \mathcal{F}_{s}\right)=\mathbb{P}\left(W_{t} \in A \mid W_{s}\right)
$$

Normality: Over finite time increments $t_{i-1}$ to $t_{i}, W_{t_{i}}-W_{t_{i-1}}$ is normally distributed with mean zero and variance $t_{i}-t_{i-1}$. \

Continuity. The paths of Brownian motion are continuous, there are no discontinuities. Brownian motion is the continuous-time limit of the discrete-time random walk. \

Non-differentiability: Almost surely (with probability 1), the paths are not differentiable at any point. Therefore, it is not possible to define $\int_{0}^{t} f(s) d W_{s}$ as $\int_{0}^{t} f(s) \frac{d W_{s}}{d s} d s$, i.e. \

## Stochastic integration \

Stochastic process:

Definition. A process $\left(H_{t}\right)_{0 \leq t \leq T}$ is a simple process if it can be written as
$$
H_{t}(\omega)=\sum_{i=1}^{p} \phi_{i}(\omega) \mathbb{I}_{\left(t_{i-1}, t_{j}\right]}(t),
$$
where $0=t_{0}<t_{1}<\cdots<t_{p}=T$ and $\phi_{i}$ is $\mathcal{F}_{t_{i-1}}$ -measurable.

Stochastic integration:

Definition. A stochastic integral of a simple pracess $H=\left(H_{t}\right)_{0 \leq t \leq T}$ is a process $\left(\int_{0}^{t} H_{s} d W_{s}\right)_{0 \leq t \leq T}$ given by
$$
\int_{0}^{t} H_{s} d W_{s}=\sum_{i=1}^{p} \phi_{i}\left(W_{t_{i} \wedge t}-W_{t_{i-1} \wedge t}\right)
$$
where $a \wedge b=\min \{a, b\}$. \

- Note that in particular $\int_{0}^{t} 1 d W_{s}=W_{t} .$ \
 
- Given a $\left(\mathcal{F}_{t}\right)_{0 \leq t \leq T}$ -Brownian motion $\left(W_{t}\right)_{0 \leq t \leq T}$ and a $\left(\mathcal{F}_{t}\right)_{0 \leq t \leq T}$ -adapted process $\left(H_{t}\right)_{0 \leq t \leq T}$, one is able to define the stochastic integral $\left(\int_{0}^{t} H_{s} d W_{s}\right)_{0 \leq t \leq T}$ as soon as $\int_{0}^{T} H_{s}^{2} d W_{s}<\infty$.
- the general concept extends that for simple processes.

## Ito's lemma

Definition. Let $(\Omega, \mathcal{F}, \mathbb{P}, \mathbb{F})$ be a filtered probability space and $\left(W_{t}\right)_{0 \leq t \leq T}$ a $\mathbb{F}$ -Brownian motion. An $\mathbb{R}$ -valued process $\left(X_{t}\right)_{0 \leq t \leq T}$ is called an Itoprocess if it can be written as
$$
X_{t}=X_{0}+\int_{0}^{t} K_{s} d s+\int_{0}^{t} H_{s} d W_{s}
$$
where
$\unrhd X_{0}$ is $\mathcal{F}_{0}$ -measurable, \
- $\left(K_{t}\right)_{0 \leq t \leq T}$ and $\left(H_{t}\right)_{0 \leq t \leq T}$ are $\left(\mathcal{F}_{t}\right)_{0 \leq t \leq T}$ -adapted processes, \
- $\int_{0}^{t}\left|K_{s}\right| d s<\infty \quad \mathbb{P}$ -a.s., \
- $\int_{0}^{t} H_{s}^{2} d s<\infty \quad \mathbb{P}-a .5 .$ \

Derivative "shorthanded" version: $dX_t=K_tdt+H_tdW_t$ \

- $dX_t$ is an increment of the process $X_t$
- Brownian motion itself is and Ito process, where $W_0$ is zero, $K_s=0$ and $H_s=1$

All this yields: 

$$
d Y_{t}=\frac{\partial f}{\partial t}\left(t, X_{t}\right) d t+\frac{\partial f}{\partial x}\left(t, X_{t}\right) d X_{t}+\frac{1}{2} \frac{\partial^{2} f}{\partial x^{2}}\left(t, X_{t}\right) d\langle X\rangle_{t}, \ (3)
$$
where the differentials are formally computed according to the following rules

$$
d t \cdot d t=d t \cdot d W_{t}=d W_{t} \cdot d t=0 \quad \text { and } \quad d W_{t} \cdot d W_{t}=d t
$$

#### Financial relevance of Ito's lemma:

Think of $X_{t}$ as some underlying financial asset and of $Y_{t}=f\left(t, X_{t}\right)$ as a new product obtained from the underlying by a possibly nonlinear transformation $f$.

Then the Ito lemma (3) shows us how the financial product reacts to changes in the underlying. 
The important message of Ito's lemma is then that when using stochastic models (for $X_{t}$ ), a simple linear approximation is not good enough, one must also account for the second order behavior of $X_{t}$. \

The trajectories of Brownian motion are of infinite variation (and finite quadratic variation) and the classical chain rule does not apply. \
One can view Ito's formula as a purely analytical result which brovides an extension of the chain rule for $f \circ x$ to functions $x$ that have a nonzero quadratic variation.

## Black-Scholes Model

### Assumptions on the assets 

- $r_f$  is constant, known and same for all maturities \
- **log return of stock prices follows an Ito process** with constant drift ($\mu$) and volatility (Normal dis.) (also implies Geometric brownian motion) \
- considering only Euro options and no dividends

### Assumptions on the market

- arbitrage free, complete, perfectly liquid and divisible
- frictionless (No TC)
- delta hedhing is performed continuosly

### Formula of B-S derived by Ito \

$S_{t}=S_{0} \cdot \exp \left(\left(\mu-\frac{1}{2} \sigma^{2}\right) t+\sigma W_{t}\right)$ \


If we want to achieve **zero randomness in self financing portfolio**, which looks like this: $d \Pi_{t}=\frac{\partial V}{\partial t}\left(t, S_{t}\right) d t+\frac{\partial V}{\partial S}\left(t, S_{t}\right) d S_{t}+\frac{1}{2} \sigma^{2} S_{t}^{2} \frac{\partial^{2} V}{\partial S^{2}}\left(t, S_{t}\right) d t-\theta_{t} d S_{t}$

Then we have to choose the proper weight theta of the short leg so the gain offset each other. This is achieved when:

$\theta_{t}=\frac{\partial V}{\partial S}\left(t, S_{t}\right):=\Delta_{V}$

- rebalanced continuosly: dynamic delta hedging

After setting up the initial portfolio, the first der of the portfolio value is:

$$
d \Pi_{t}=\left(\frac{\partial V}{\partial t}\left(t, S_{t}\right)+\frac{1}{2} \sigma^{2} S_{t}^{2} \frac{\partial^{2} V}{\partial S^{2}}\left(t, S_{t}\right)\right) d t .
$$

#### Black scholes Partial differentail equaiton (PDE) \

We should know the proof. Consult L06,s.37-41.

B-S PDE = $$
\frac{\partial V}{\partial t}\left(t, S_{t}\right)+\frac{1}{2} \sigma^{2} S_{t}^{2} \frac{\partial^{2} V}{\partial S^{2}}\left(t, S_{t}\right)+r S_{t} \frac{\partial V}{\partial S}\left(t, S_{t}\right)-r V\left(t, S_{t}\right)=0
$$


- B-S does not depend on $\mu$ !!

## Black-scholes by Martingale \

This yields the Black-Scholes formula for call options:
$$
C\left(t, S_{t}\right)=S_{t} \Phi\left(d_{1}\right)-K e^{-r(T-t)} \Phi\left(d_{2}\right)
$$
where
$$
d_{1}=\frac{\ln \left(\frac{S_{t}}{K}\right)+\left(r+\frac{\sigma^{2}}{2}\right)(T-t)}{\sigma \sqrt{T-t}}
$$
and
$$
d_{2}=d_{1}-\sigma \sqrt{T-t}
$$
$\Phi(\cdot)$ denotes the cdf of a $\mathcal{N}(0,1)$ distributed random variable
$$
\Phi(x):=\frac{1}{\sqrt{2 \pi}} \int_{-\infty}^{x} e^{-\frac{s^{2}}{2}} d s
$$

Alternatively, we can derive it using the put-call parity relation
$$
C\left(t, S_{t}\right)-P\left(t, S_{t}\right)=S_{t}-K \cdot e^{-r(T-t)} .
$$
The put option price is
$$
P\left(t, S_{t}\right)=K \cdot e^{-r(T-t)} \cdot \Phi\left(-d_{2}\right)-S_{t} \cdot \Phi\left(-d_{1}\right) .
$$

# Risk measures \

**Risk** is "any event or action that may adversely affect an organization's ability to achieve its objectives and execute its strategies"

#### Approaches to Risk measurement: \

- notional-amount approach: the risk of a portfolio is defined as the (weighted) sum of the notionl values of the individual securities
- factor sensitivity measures: give the change in portfolio value for a given predertmined change in one of the underlying risk factors
- scenario-based risk measures: one considers a number of future scenarios and measures the maximum loss of the portfolio under these scenarios
- risk measures based on loss distributions: stat. quantities describin characteristics of the loss distribution of the portfolio

In our (CARM) interpreation, risk measures how much capital to inject to become adequately capitalized (under some regulations)

### Three pillar concept under Basel 2

- minimal capital charge: requirements for the calculation of the regulatory capital to ensure that a bank holds sufficient capital for its credit risk in the banking book its market risk in the trading book and operational risk
- supervisory review process: local rergulators review the check and balances put in place for capital adequacy assessments, ensure that banks have adequate reg. capital and perform stress tests of a bank's capital adequacy
- market discipline: banks are required to make their risk management processes more transparent

### Reasons for Corp Risk management (turning M&M upside down)

- RM can reduce taxes
- RM is beneficial coz of better access to cap. markets
- RM increases value in presence of bankrupcy costs (lower excpted value coz of lower P(default))
- RM reduces impact of costly external financing

## Acceptance set 

Definition. A set $\mathcal{A}$ of random variables is called an acceptance set if \
$\triangleright \mathcal{A}$ is non-trivial, i.e. $\mathcal{A} \neq \emptyset$ and $\mathcal{A} \subsetneq \mathcal{X}$, \
$\triangleright \mathcal{A}$ is monotone, i.e. $X \in \mathcal{A}, Y \geq X \Longrightarrow Y \in \mathcal{A}$ (if X us acceptable and Y=X+100, X is also acceptable) \

By $Y \geq X$ we mean either $Y(\omega) \geq X(\omega)$ for all $\omega \in \Omega$, or $\mathbb{P}$ -almost surely.
The acceptance set is specified by the regulator. \

An acceptance set is called: (L08, 17 for pictures)

- *cone* if $X_{T} \in \mathcal{A} \Longrightarrow \forall \lambda>0: \lambda X_{T} \in \mathcal{A}$
- *convex* if $X_{T}, Y_{T} \in \mathcal{A} \Longrightarrow \forall \lambda \in[0,1]: \lambda X_{T}+(1-\lambda) Y_{T} \in \mathcal{A}$
- *closed* if $\mathcal{A}=\overline{\mathcal{A}},$ \

## VaR 

$VaR_\alpha(X)=-\mu - \sigma \phi^{-1}(\alpha)$

- Finding var: order the outcomes (returns/cap positions) in a decreasing order. Start from the first and add probabilites until they are **stricly greater than $\alpha$**. Once they are, take the corresponsing $X_n * -1$ and that is VaR at level alpha.


### Remarks

- VaR does not account for severity of losses with prob $1-\alpha$
- VaR does not account for diversification
- VaR is not convex, hence not coherent - might penalize diversification
- Simon Johnson (MIT):" VaR misses everything that matters when it matters"


## Expected shortfal ES

$$
\mathcal{A}_{\mathrm{ES}_{\alpha}}:=\left\{X \in \mathcal{X} \mid \frac{1}{\alpha} \int_{0}^{\alpha} \operatorname{VaR}_{\beta}(X) \mathrm{d} \beta \leq 0\right\}
$$

$$
ES_\alpha(X)=-\mu+\frac{\sigma}{\alpha} \Phi^{\prime}\left(\Phi^{-1}(\alpha)\right)
$$

An acceptance set $\mathcal{A}$ is said to be coherent if it is \
- convex: $X, Y \in \mathcal{A}, 0<\lambda<1 \Longrightarrow \lambda X+(1-\lambda) Y \in \mathcal{A}$, \
- conic: $X \in \mathcal{A}, \lambda \geq 0 \Rightarrow \lambda X \in \mathcal{A}$ \
Financial interpretation: \
- Convexity means that portfolios of acceptable positions are still acceptable, i.e. acceptability is preserved by diversification. \
- Conicity means that acceptability is independent of the position size.\


# Mean-variance Portfolio/Optimization MVP

- we are risk averse but like money. Described by utility functions. Second deriv is $\leq$ 0. Thus, function mus be increasing and convave (slide 5)

## Diversification principle

$$
X=\left\{\begin{array}{ll}
2 m & \text { coin shows heads } \\
0 & \text { coin shows tails. }
\end{array} \quad Y=\left\{\begin{array}{ll}
0 & \text { coin shows heads } \\
2 m & \text { coin shows tails. }
\end{array}\right.\right.
$$
Play both at once. Invest  $\frac{m}{2}$ in either game, total of $m$ invested. The new payoff is given by
$$
\frac{1}{2} X+\frac{1}{2} Y=\left\{\begin{array}{ll}
m & \text { coin shows heads } \\
m & \text { coin shows tails. }
\end{array}\right.
$$
So in either case, we get our money back! The payoff is constant. Hence,
$$
\begin{array}{ll}
\text { Expectation: } & \mathbb{E}\left[\frac{1}{2}(X+Y)\right]=\frac{1}{2} \cdot m+\frac{1}{2} \cdot m=m \\
\text { Variance: } & \mathbb{V}\left[\frac{1}{2}(X+Y)\right]=\frac{1}{2} \cdot m^{2}+\frac{1}{2} \cdot m^{2}-m^{2}=0
\end{array}
$$


We achieved diversification because of perfect negative correlation, which is a necessary, but not a sufficient condition.

$$
\begin{aligned}
\rho x, Y &:=\operatorname{corr}(X, Y):=\frac{\operatorname{Cov}(\mathrm{X}, \mathrm{Y})}{\sqrt{\mathbb{V}[X] \mathbb{V}[Y]}}:=\frac{\mathbb{E}[(X-\overbrace{\mathbb{E}[X]}^{=m})(Y-\overbrace{\mathbb{E}[Y]}^{=m})]}{m \cdot m} \\
&=\frac{\mathbb{E}\left[X Y-m X-m Y+m^{2}\right]}{m^{2}}=\frac{\mathbb{E}[X Y]-m^{2}-m^{2}+m^{2}}{m^{2}} \\
&=\frac{0-m^{2}}{m^{2}}=-1
\end{aligned}
$$

## Always to remember assumptions

- preference to increase consumption
- risk-aversion
- therefore, utility functions are concave

- **an investor maximies the portfolio's expected return for a given level of variance or vice versa, minimses the variance for a given level of expected return**.

## Var-Covar matrix

- Finally, we need one more ingredient. The covariance between two returns $\ell, m \in\{1, \ldots, M\}$ is defined as
$\operatorname{Cov}\left(R_{T, \ell}, R_{T, m}\right)=\sum_{n=1}^{N} p_{n}\left(R_{T, \ell}\left(\omega_{n}\right)-\mathbb{E}\left[R_{T, \ell}\right]\right)\left(R_{T, m}\left(\omega_{n}\right)-\mathbb{E}\left[R_{T, m}\right]\right)$
We assemble the individual covariances in the covariance matrix $\operatorname{Cov}\left(\mathbf{R}_{T}\right) \in \mathbb{R}^{M \times M}$ of the random vector,
$\operatorname{Cov}\left(\mathbf{R}_{T}\right)=\left[\begin{array}{cccc}\operatorname{Cov}\left(R_{T, 1}, R_{T, 1}\right) & \operatorname{Cov}\left(R_{T, 1}, R_{T, 2}\right) & \cdots & \operatorname{Cov}\left(R_{T, 1}, R_{T, M}\right) \\ \operatorname{Cov}\left(R_{T, 2}, R_{T, 1}\right) & \operatorname{Cov}\left(R_{T, 2}, R_{T, 2}\right) & \cdots & \operatorname{Cov}\left(R_{T, 2}, R_{T, M}\right) \\ \vdots & \vdots & \ddots & \vdots \\ \operatorname{Cov}\left(R_{T, M}, R_{T, 1}\right) & \operatorname{Cov}\left(R_{T, M}, R_{T, 2}\right) & \cdots & \operatorname{Cov}\left(R_{T, M}, R_{T, M}\right)\end{array}\right.$ \
 Note that $\operatorname{Cov}\left(R_{T, m}, R_{T, m}\right)=\mathbb{V}\left[R_{T, m}\right]$, and thus, the diagonal of $\operatorname{Cov}\left(\mathbf{R}_{T}\right)$ is the variance vector, $\operatorname{diag}\left(\operatorname{Cov}\left(\mathbf{R}_{T}\right)\right)=\mathbb{V}\left[\mathbf{R}_{T}\right] .$

## Implementation

**portfolio** is a *linear combination* of all individual assets. Coefficient $\alpha$ denote the weights. We investing all our wealth, i.e. sum of alphas = 1

Simple return of the portfolio:

$$
\begin{aligned}
R_{T}^{\alpha} &=\frac{P_{T}^{\alpha}}{P_{0}^{\alpha}}-1=\frac{\sum_{m=1}^{M} \frac{\alpha_{m} W}{P_{0, m}} P_{T, m}}{W}-\sum_{m=1}^{M} \alpha_{m} \\
&=\sum_{m=1}^{M} \alpha_{m} \underbrace{\left(\frac{P_{T, m}}{P_{0, m}}-1\right)}_{=R_{T, m}}=\sum_{m=1}^{M} \alpha_{m} R_{T, m} .
\end{aligned}
$$

$$
\mathbb{E}\left[R_{T}^{\alpha}\right]=\sum_{n=1}^{N} p_{n} R_{T}^{\alpha}\left(\omega_{n}\right)
$$

### Portfolio's return as linear combination of individual expectations.

Showing that expectation of the portfolio's returns

Based on the result from the previous exercise, we can write $R_{T}^{\alpha}$ as the linear combination of the individual returns,
$$
\begin{aligned}
\mathbb{E}\left[R_{T}^{\alpha}\right] &=\sum_{n=1}^{N} p_{n} R_{T}^{\alpha}\left(\omega_{n}\right)=\sum_{n=1}^{N} p_{n} \sum_{m=1}^{M} \alpha_{m} R_{T, m}\left(\omega_{n}\right) \\
&=\sum_{m=1}^{M} \alpha_{m} \underbrace{\sum_{n=1}^{N} p_{n} R_{T, m}\left(\omega_{n}\right)}_{=\mathbb{E}\left[R_{T, m}\right]}=\sum_{m=1}^{M} \alpha_{m} \mathbb{E}\left[R_{T, m}\right]=\boldsymbol{\alpha}^{T} \mathbb{E}\left[\mathbf{R}_{T}\right] .
\end{aligned}
$$$



### Variance of the portfolio's returns (proof s.59)

$$
\mathbb{V}\left[R_{T}^{\alpha}\right]=\sum_{\ell=1}^{M} \sum_{m=1}^{M} \alpha_{\ell} \alpha_{m} \operatorname{Cov}\left(R_{T, \ell}, R_{T, m}\right)=\boldsymbol{\alpha}^{\top} \operatorname{Cov}\left(\mathbf{R}_{T}\right) \boldsymbol{\alpha}
$$

### Constrained optimasation (Markowitz' port. optimization problem / MVO)

M-V is a **constrained optimisation problem**:

- minimise or maxise an objective function over all possible portfolio combinations, hence, over all possible weight vectors $\alpha$ 
- The optimisations are subject to a set of constraints $$ \mathcal{C}$$

#### First way: minimize risk for set return MV-Min

We only have a budget (wealth) and an objective constraint (fixing return). Arbitrary short-selling is allowed.
$$
\mathcal{C}_{\mathrm{E}}=\left\{\mathbf{1}^{\top} \boldsymbol{\alpha}=1, \quad \mathbb{E}\left[R_{T}^{\alpha}\right] \geq E^{*} \text { for some fixed } E^{*} \in \mathbb{R}\right\}; \text { where  } E^{*} \text{is our required return}
$$

Choosing too large required return can lead to empty set. In words, the first contraint (budget) requires alphas to sum up to 1. The second say expected return is no less than the target.

#### Second way: maximize return for set risk MV-Max

$$
\mathcal{C}_{\mathrm{V}}=\left\{\mathbf{1}^{\boldsymbol{\top}} \boldsymbol{\alpha}=1, \quad \mathbb{V}\left[R_{t}^{\alpha}\right] \leq \boldsymbol{V}^{*} \text { for some fixed } V^{*}>0\right\} \text { . }
$$

##### Example 

$$
\begin{array}{|c|c|c|}
\hline \text { Stock } & \text { Expected Return } & \text { Standard Deviation } \\
\hline \text { A } & \mu_{A}=10 \% & \sigma_{A}=5 \% \\
\hline \text { B } & \mu_{B}=15 \% & \sigma_{B}=10 \% \\
\hline
\end{array}
$$
Correlation $\rho=-1$


$$
\mu=\left(\begin{array}{l}
\mu_{A} \\
\mu_{B}
\end{array}\right)=\left(\begin{array}{c}
0.1 \\
0.15
\end{array}\right) \text { and } \Sigma=\left(\begin{array}{cc}
\sigma_{A}^{2} & \sigma_{A} \sigma_{B} \rho \\
\sigma_{A} \sigma_{B} \rho & \sigma_{B}^{2}
\end{array}\right)=\left(\begin{array}{cc}
0.0025 & -0.005 \\
-0.005 & 0.01
\end{array}\right)
$$

Setting the weights of the portfolio $\omega=\left(\omega_{A}, \omega_{B}\right)^{\top}$, the variance of the portfolio is given by

$$
\begin{aligned}
\sigma_{p}^{2} &=\omega^{\top} \Sigma \omega=\left(\begin{array}{ll}
\omega_{A} & \omega_{B}
\end{array}\right)\left(\begin{array}{cc}
\sigma_{A}^{2} & \sigma_{A} \sigma_{B \rho} \\
\sigma_{A} \sigma_{B} \rho & \sigma_{B}^{2}
\end{array}\right)\left(\begin{array}{l}
\omega_{A} \\
\omega_{B}
\end{array}\right) \\
&=\omega_{A}^{2} \sigma_{A}^{2}+2 \omega_{A} \omega_{B} \sigma_{A} \sigma_{B} \rho+\omega_{B}^{2} \sigma_{B}^{2} \\
&=\omega_{A}^{2} \cdot 0.0025-\omega_{A} \omega_{B} \cdot 0.01+\omega_{B}^{2} \cdot 0.01 \\
&=\left(0.05 \omega_{A}-0.1 \omega_{B}\right)^{2}
\end{aligned}
$$


